model_params:
  name: 'VanillaVAE'
  in_channels: 6
  latent_dim: 20 

exp_params:
  dataset: probes
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
